version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/app-directory/specification/test
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /toolbox/fdc3-workbench
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
