name: Node.js CVE Scanning

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'package.json'
      - 'toolbox/fdc3-workbench/package.json'
      - '.github/workflows/cve-scanning.yml'
      - 'website/package.json'
  # push:
  #   paths:
  #     - 'package.json'
  #     - 'toolbox/fdc3-workbench/package.json'
  #     - '.github/workflows/cve-scanning.yml'
  #     - 'website/package.json'
  schedule:
    # Run every day at 5am and 5pm
    - cron: '0 5,17 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm install
      
      - run: npm install
        working-directory: toolbox/fdc3-workbench

      - run: npm install
        working-directory: website

      - run: npx --yes auditjs ossi --whitelist allow-list.json
        if: success() || failure()

      - run: npx --yes auditjs ossi --whitelist ../../allow-list.json
        working-directory: toolbox/fdc3-workbench
        if: success() || failure()
        
      - run: npx --yes auditjs ossi --whitelist ../allow-list.json
        working-directory: website
        if: success() || failure()
