name: Static code analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  schedule:
    # Run every day at 5am and 5pm
    - cron: '0 5,17 * * *'

permissions:
  contents: read

jobs:
  semgrep:
    name: run-semgrep
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - run: semgrep scan --error --config auto
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
